-- 015 · Broker lead inbox + one broker identity (2026-08-05)
-- Spec: docs/superpowers/specs/2026-08-05-broker-lead-inbox-design.md
-- Plan: docs/superpowers/plans/2026-08-05-broker-lead-inbox.md
--
-- RUN BEFORE DEPLOYING the inbox routes. Verify with `node migrations/verify.js`.

-- ---------------------------------------------------------------------------
-- 1. One broker identity. broker_profiles was keyed on email alone (003);
-- the paid tier keys on user_id. This links them: profiles follow the account,
-- not the address. `on delete set null` (not cascade): a profile is public
-- content already cited in reports; losing the account should not vaporize it.
-- ---------------------------------------------------------------------------
alter table broker_profiles
  add column if not exists user_id uuid references users(id) on delete set null;

create unique index if not exists broker_profiles_user_id_uidx
  on broker_profiles (user_id) where user_id is not null;

-- Backfill: adopt every profile whose email matches an account.
-- broker_profiles.email is stored lowercased (003); lower() the users side.
update broker_profiles p
   set user_id = u.id
  from users u
 where p.user_id is null
   and lower(u.email) = p.email;

-- ---------------------------------------------------------------------------
-- 2. Lead size. Nullable: old leads and sizeless searches simply have none.
-- ---------------------------------------------------------------------------
alter table leads add column if not exists size_sqft numeric;

-- The leads table predates the migrations folder (000, hand-created). The
-- inbox needs a stable per-row id for lead_intro_requests.lead_id. Supabase
-- dashboard tables get `id bigint identity primary key` by default; this
-- guard only fires if this one somehow did not.
do $$
begin
  if not exists (select 1 from information_schema.table_constraints
                 where table_name = 'leads' and constraint_type = 'PRIMARY KEY') then
    alter table leads add column if not exists id bigint generated by default as identity;
    alter table leads add primary key (id);
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 3. Coverage: which market+type pairs a broker sees leads for.
-- `source`: 'earned' (seeded from approved submissions) | 'chosen' (added by
-- the broker). market is canonical marketOf() form, same as broker_comps.
-- ---------------------------------------------------------------------------
create table broker_coverage (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id) on delete cascade,
  market text not null,
  property_type text not null,
  source text not null default 'chosen',
  created_at timestamptz not null default now(),
  unique (user_id, market, property_type)
);
-- "Who covers this market" at lead-capture time.
create index on broker_coverage (market, property_type);
alter table broker_coverage enable row level security;

-- ---------------------------------------------------------------------------
-- 4. Introduction requests. No FK to leads: its PK type is verified, not
-- assumed (see the guard above), and a dangling id is harmless — the join is
-- done in server.js and a missing lead simply renders nothing.
-- unique(lead_id, user_id): a second click is a 409, answered as already:true,
-- never a second email to the owner.
-- ---------------------------------------------------------------------------
create table lead_intro_requests (
  id uuid primary key default gen_random_uuid(),
  lead_id bigint not null,
  user_id uuid not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (lead_id, user_id)
);
create index on lead_intro_requests (user_id);
alter table lead_intro_requests enable row level security;

-- Verify (zero rows = schema complete):
--   select t from unnest(array['broker_coverage','lead_intro_requests']) as t
--   where not exists (select 1 from information_schema.tables
--                     where table_name = t);
--   select c from unnest(array['user_id']) as c
--   where not exists (select 1 from information_schema.columns
--                     where table_name = 'broker_profiles' and column_name = c);
--   select c from unnest(array['size_sqft']) as c
--   where not exists (select 1 from information_schema.columns
--                     where table_name = 'leads' and column_name = c);
